name: Complete CI-CD
on:
  push:
    branches:
        -main
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: NodeJS setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
        
      - name: Install packages
        run: npm install
  
      - name: Run tests
        run: npm run check -- --report>report.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage.txt

